### ISSUE TITLE
Document how to disable JGroups

### ISSUE THREAD

**Issue by cbeach47** [uPortal-Project/uPortal-start#336]
This is related to https://github.com/Jasig/uPortal/issues/1739 .

Adopters would like to disable JGroups with minimal effort.

Generate documentation on how use the file from uP#1739 to disable JGroups.

**Comment by bjagg** [comment]
For overridesContext.xml, add a custom `cacheManager` which is the same as the default in uPortal, but with the `depends-on="systemPropertySetter"` instead of `depends-on="systemPropertySetter, authDao"`:

```  
 <bean id="cacheManager" class="org.springframework.cache.ehcache.EhCacheManagerFactoryBean"
          depends-on="systemPropertySetter"
          p:shared="true"
          p:configLocation="classpath:/properties/ehcache.xml" />
```

**Comment by bjagg** [comment]
Copy uPortal `uPortal-webapp/src/main/resources/properties/ehcache.xml` to uPortal-start `overlays/uPortal/src/main/resources/properties/ehcache.xml`.

Then make the following edits:
1. Remove or comment out the following:
```
     <cacheManagerPeerProviderFactory
         class="net.sf.ehcache.distribution.jgroups.JGroupsCacheManagerPeerProviderFactory"
         properties="file=properties/jgroups.xml" />
```

2. remove all `JGroupsCacheReplicatorFactory` entries:
```
         <cacheEventListenerFactory
             class="net.sf.ehcache.distribution.jgroups.JGroupsCacheReplicatorFactory"
             properties="replicateAsynchronously=true,
                 replicatePuts=false,
                 replicateUpdates=true, replicateUpdatesViaCopy=false,
                 replicateRemovals=true "/>
```

**Comment by bjagg** [comment]
[ehcache-no-jgroups.txt](https://github.com/Jasig/uPortal-start/files/3895080/ehcache-no-jgroups.txt)
