### ISSUE TITLE
Add IPv4 preference to setenv scripts

### ISSUE THREAD

**Issue by bjagg** [uPortal-Project/uPortal-start#378]
**Is your feature request related to a problem? Please describe.**
Most deployments require IPv4 rather than IPv6. This should be configured as the the default.

**Describe the solution you'd like**
Add the following to etc/tomcat/bin/setenv.sh and etc/tomcat/bin/setenv.bat:
`-Djava.net.preferIPv4Stack=true`
`-Djava.net.preferIPv4Addresses=true`

**Comment by jonathanmtran** [comment]
Resolved via 13c55e4
