### ISSUE TITLE
Java 8u332 fails to generate doctype, results in layout issues

### ISSUE THREAD

**Issue by cbeach47** [uPortal-Project/uPortal-start#570]
Running the portal on Java 8u332 causes uPortal to return html pages without the doctype declaration, which makes the browser go into Quirks mode, and a console message notes there may be some layout issues. 

Some specific layout issues with Java 8u332 have been experienced with the icon size for the search widget, and extra space in portlets (such as Announcement Admin).

Running with Java 8u292 causes Tomcat / uPortal to return the doctype, and does not display the layout issues.

Workaround is not to upgrade Java install past 8u292 until this issue is sorted out.

**Comment by bjagg** [comment]
Using Java 8u275
```
$ java -version
openjdk version "1.8.0_275"
```

Doctype is `<!DOCTYPE html SYSTEM "EMPTY">`

**Comment by jonathanmtran** [comment]
```
$ java -version
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.322-b06, mixed mode)
```

results in the following

```
<!DOCTYPE html SYSTEM "EMPTY">
```

**Comment by jgribonvald** [comment]
from debian, installed with SDKman:
```
$ java -version
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_332-b09)
OpenJDK 64-Bit Server VM (Temurin)(build 25.332-b09, mixed mode)

**Comment by bjagg** [comment]
https://github.com/uPortal-Project/uPortal/blob/master/uPortal-webapp/src/main/resources/layout/theme/respondr/respondr.xsl#L115

This line generates the Doctype. It depends on Xalan from what I can tell. Trying to force an HTML 5 compatible Doctype doesn't seem to work with various attributes on this line. Trying to add an explicit <xsl:text> line in the `/` template fails as well.

**Comment by bjagg** [comment]
Reference: http://www.microhowto.info/howto/generate_an_html5_doctype_using_xslt.html

**Comment by cbeach47** [comment]
Part of the uP 5.12.0 release.
